import bcrypt from 'bcryptjs'
const data = {
  users:[
      {
        name:'Michael',
        email:'admin@example.com',
        password: bcrypt.hashSync('password', 8),
        isAdmin: true,
      },
      {
        name:'Rhema',
        email:'user@example.com',
        password: bcrypt.hashSync('1234', 8),
        isAdmin: true,
      }
  ],
  products: [
    {
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/img1.jpg',
      countInStock: 10,
      price: 120,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/img2.jpg',
      countInStock: 20,
      price: 100,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/img3.jpg',
      countInStock: 80,
      price: 220,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/img4.jpg',
      countInStock: 0,
      price: 78,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/img5.jpg',
      countInStock: 15,
      price: 65,
      brand: 'Puma',
      rating: 2.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/img6.jpg',
      countInStock: 10,
      price: 139,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
        name: 'Nike Slim Pant',
        category: 'Pants',
        image: '/images/img4.jpg',
        countInStock: 1,       
        price: 78,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 14,
        description: 'high quality product',
      },
      {

        name: 'Nike Slim Shirt',
        category: 'Shirts',
        image: '/images/img1.jpg', 
        countInStock: 0,       
        price: 120,
        brand: 'Nike',
        rating: 4.5,
        numReviews: 10,
        description: 'high quality product',
      },
  ],
};
export default data;